version: '3.8'

services:
  nginx:
    image: nginx:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites/:/etc/nginx/sites/:ro
    networks:
      - meu-projeto-network
    restart: always

networks:
  meu-projeto-network:
    external: true